### PR TITLE
Hw 10

### PR DESCRIPTION
**Pull request by Riggy0508**
Completed HW-10, please review

### CODE REVIEW

**Comment by adamTrz** [comment]
Hi @Riggy0508 
Could you please merge #10 and rebase please? :)

**Comment by Riggy0508** [comment]
Hi @adamTrz,
I have merged the PR.

**Comment by Wiiktor22** [comment]
Hi @Riggy0508!
Could you please rebase this branch with your main branch, so this PR will include only the commit with completed Homework 10? Please ping me once you rebased. 
Thank you!

**Comment by Wiiktor22** [comment]
Hi @Riggy0508, 

I've checked your homework implementation for module 10, it looks almost complete.
Could you please confirm whether the tests are passing for you after applying modifications related to theming and animations? [In our implementation](https://github.com/callstack-workshops/abbott-module-10-homework), we have provided a set of changes in order to satisfy tests after bringing new changes. We've provided mocks for the reanimated library, and we have set up a pre-configured theme for the testing environment. Please make sure to double-check that!

Otherwise, it looks fine! 🚀

**Review by Wiiktor22 — CHANGES_REQUESTED** [review]
Please double check the state of tests, after bringing new modifications.

**Pull request merged**
